version: 2

updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    allow:
      - dependency-name: '@marp-team/*'
    versioning-strategy: increase

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    # versioning-strategy: increase-if-necessary
    open-pull-requests-limit: 0 # Dependabot does not allow relaxed versioning :(
