extends:
  - stylelint-config-standard-scss

rules:
  at-rule-no-unknown:
    - null
  color-function-notation:
    - null
  scss/at-rule-no-unknown:
    - true
  value-keyword-case:
    - lower
    - ignoreProperties:
        - /^--/
  no-invalid-position-at-import-rule:
    - null
